language: dart
dart:
    - stable
os:
    - linux
sudo: false
addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - libstdc++6
        - fonts-droid
install:
    - eval BUILD_DIR=\$${TRAVIS_BUILD_DIR}
    - echo 'Testing {$BUILD_DIR}'
before_script:
    - cd ..
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
script:
    - cd $TRAVIS_BUILD_DIR
    - echo 'Running linter analasis...'
    - flutter analyze
    - echo 'Running tests...'
    - flutter test
cache:
    directories:
    - $HOME/.pub-cache