language: dart
dart:
    - stable
os:
    - linux
sudo: false
addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - libstdc++6
        - fonts-droid
install:
    - echo 'Testing SplitterFlutter'
before_script:
    - ls
    - cd ..
    - ls
    - git clone https://github.com/flutter/flutter.git -b stable
    - ls
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
script:
    - ls
    - cd SplitterFlutter
    - ls
    - flutter analyze --no-pub --no-current-package lib
    - flutter test
cache:
    directories:
    - $HOME/.pub-cache