os: linux
language: dart
dist: xenial
addons:
  apt:
    packages:
    - lib32stdc++6
install:
- git clone https://github.com/flutter/flutter.git
- ./flutter/bin/flutter doctor
script:
- cd app
- ../flutter/bin/flutter test
cache:
  directories:
  - $HOME/.pub-cache