language: dart
dart:
    - stable
os:
    - linux
sudo: false
addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - libstdc++6
        - fonts-droid
install:
    - echo 'Testing SplitterFlutter'
before_script:
    - cd ..
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
script:
    - echo 'Travis build DIR'
    - echo $TRAVIS_BUILD_DIR
    - echo 'Cleaning project...'
    - flutter clean
    - echo 'Updating packages...'
    - flutter clean
    - cd $TRAVIS_BUILD_DIR
    - echo 'Running linter analysis...'
    - flutter analyze
    - echo 'Running tests...'
    - flutter test
cache:
    directories:
    - $HOME/.pub-cache