language: dart
dart:
    - stable
os:
    - linux
sudo: false
addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - libstdc++6
        - fonts-droid
install:
  - echo 'Avoid default Travis CI install step'
before_script:
    - cd ..
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
script:
    - cd $TRAVIS_BUILD_DIR
    - echo 'Getting packages'
    - flutter packages get
    - echo 'Running linter analysis...'
    - flutter analyze --no-pub --no-current-package lib
    - echo 'Running tests...'
    - flutter test
    # - echo 'Publishing packages'
    # - flutter packages pub publish --dry-run
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: '../.travis/publish.sh'
#   on:
#     tags: true
cache:
    directories:
    - $HOME/.pub-cache